config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :clothings

  root 'clothings#index'
  

end

app/models/clothing.rb
class Clothing < ActiveRecord::Base
	scope :tops, -> { where(category: 'top') }
	scope :bottoms, -> { where(category: 'bottom') }
	scope :onepiece, -> { where(category: 'onepiece') }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/clothings_controller.rb
class ClothingsController < ApplicationController
  before_action :set_clothing, only: [:show, :edit, :update, :destroy]
  # protect_from_forgery with: :null_session
  # skip_before_action :verify_authenticity_token, only: [:create]
  skip_before_action :verify_authenticity_token, if: :json_request?
  


  # GET /clothings
  # GET /clothings.json
  def index
    @clothings = Clothing.all
  end

  # GET /clothings/1
  # GET /clothings/1.json
  def show
  end

  # GET /clothings/new
  def new
    @clothing = Clothing.new
  end

  # GET /clothings/1/edit
  def edit
  end

  # POST /clothings
  # POST /clothings.json
  def create
    logger.info request.env
    @clothing = Clothing.new(clothing_params)

    respond_to do |format|
      if @clothing.save
        format.html { redirect_to @clothing, notice: 'Clothing was successfully created.' }
        format.json { render :show, status: :created, location: @clothing }
      else
        format.html { render :new }
        format.json { render json: @clothing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clothings/1
  # PATCH/PUT /clothings/1.json
  def update
    respond_to do |format|
      if @clothing.update(clothing_params)
        format.html { redirect_to @clothing, notice: 'Clothing was successfully updated.' }
        format.json { render :show, status: :ok, location: @clothing }
      else
        format.html { render :edit }
        format.json { render json: @clothing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clothings/1
  # DELETE /clothings/1.json
  def destroy
    @clothing.destroy
    respond_to do |format|
      format.html { redirect_to clothings_url, notice: 'Clothing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  protected

  def json_request? 
    request.format.json?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clothing
      @clothing = Clothing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clothing_params
      params.require(:clothing).permit(:category, :style, :brand, :color, :seasons, :work_approp, :layerable)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clothings_helper.rb
module ClothingsHelper
end

app/views/clothings/_form.html.erb
<%= form_for(@clothing) do |f| %>
  <% if @clothing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clothing.errors.count, "error") %> prohibited this clothing from being saved:</h2>

      <ul>
      <% @clothing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :style %><br>
    <%= f.text_field :style %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :seasons %><br>
    <%= f.text_field :seasons %>
  </div>
  <div class="field">
    <%= f.label :work_approp %><br>
    <%= f.check_box :work_approp %>
  </div>
  <div class="field">
    <%= f.label :layerable %><br>
    <%= f.check_box :layerable %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clothings/edit.html.erb
<h1>Editing Clothing</h1>

<%= render 'form' %>

<%= link_to 'Show', @clothing %> |
<%= link_to 'Back', clothings_path %>

app/views/clothings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clothings</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Style</th>
      <th>Brand</th>
      <th>Color</th>
      <th>Seasons</th>
      <th>Work approp</th>
      <th>Layerable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clothings.each do |clothing| %>
      <tr>
        <td><%= clothing.category %></td>
        <td><%= clothing.style %></td>
        <td><%= clothing.brand %></td>
        <td><%= clothing.color %></td>
        <td><%= clothing.seasons %></td>
        <td><%= clothing.work_approp %></td>
        <td><%= clothing.layerable %></td>
        <td><%= link_to 'Show', clothing %></td>
        <td><%= link_to 'Edit', edit_clothing_path(clothing) %></td>
        <td><%= link_to 'Destroy', clothing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clothing', new_clothing_path %>

app/views/clothings/new.html.erb
<h1>New Clothing</h1>

<%= render 'form' %>

<%= link_to 'Back', clothings_path %>

app/views/clothings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @clothing.category %>
</p>

<p>
  <strong>Style:</strong>
  <%= @clothing.style %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @clothing.brand %>
</p>

<p>
  <strong>Color:</strong>
  <%= @clothing.color %>
</p>

<p>
  <strong>Seasons:</strong>
  <%= @clothing.seasons %>
</p>

<p>
  <strong>Work appropriate:</strong>
  <%= @clothing.work_approp %>
</p>

<p>
  <strong>Layerable:</strong>
  <%= @clothing.layerable %>
</p>

<%= link_to 'Edit', edit_clothing_path(@clothing) %> |
<%= link_to 'Back', clothings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WhatToWearApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>